# Generated by Django 2.1.4 on 2019-10-25 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tank_Name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Tank_Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True)),
                ('Time', models.TimeField(auto_now_add=True)),
                ('Tank_Reading_Recieved', models.PositiveIntegerField()),
                ('Tank_Name', models.CharField(default='', max_length=25)),
                ('Tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tank', to='watermoduleapp.Tank')),
            ],
        ),
    ]
